// flow-typed signature: d32d32113ed91b61fdabed09b628b2a4
// flow-typed version: <<STUB>>/lodash.reduce_v^4.6.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.reduce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.reduce' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.reduce/index' {
  declare module.exports: $Exports<'lodash.reduce'>
}
declare module 'lodash.reduce/index.js' {
  declare module.exports: $Exports<'lodash.reduce'>
}
