// flow-typed signature: 3b41f4ed103399d7fd7e48c992e142bd
// flow-typed version: <<STUB>>/lodash.foreach_v^4.5.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.foreach'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.foreach' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.foreach/index' {
  declare module.exports: $Exports<'lodash.foreach'>
}
declare module 'lodash.foreach/index.js' {
  declare module.exports: $Exports<'lodash.foreach'>
}
